<?xml version= "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_width"  value="0.05"/>
    <xacro:property name="base_length"  value="0.6"/>
    <xacro:property name="base_width"  value="0.4"/>
    <xacro:property name="base_height"  value="0.2"/>

    <link name= "base_footprint_link">
        <visual>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </visual>
    </link>

    <link name= "base_link">
        <visual>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}" /> <!-- all dimensions are in meters -->
            </geometry>
            <origin xyz = "0 0 0.1" rpy = "0 0 0"/>
            <material name= "blue" />
        </visual>
        <collision>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}" /> <!-- all dimensions are in meters -->
            </geometry>
            <origin xyz = "0 0 0.1" rpy = "0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}"
                            o_xyz="0 0 ${base_height / 2}" o_rpy="0 0 0" 
        />
    </link>

    <link name= "imu_link">
        <visual>
                <geometry>
                    <box size = "0.2 0.1 0.05" />
                </geometry>
            <origin xyz = "0 0 0.025" rpy = "0 0 0"/>
            <material name= "green" />
        </visual>
        <collision>
            <geometry>
                <box size = "0.2 0.1 0.05" />
            </geometry>
            <origin xyz = "0 0 0.025" rpy = "0 0 0"/>
        </collision>
        <xacro:box_inertia m="0.2" x="${base_height}" y="${base_height / 2}" z="0.05"
                            o_xyz="0 0 0.025" o_rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix name" >
        <link name= "${prefix}${name}">
            <visual>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2} 0 0"/>
                <material name= "black" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius = "${wheel_radius}"/>
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2} 0 0"/>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.5"/>
                <inertia
                    ixx="${0.5 * 0.5 * wheel_radius * wheel_radius}"
                    iyy="${(1/12) * 0.5 * (3 * wheel_radius * wheel_radius + wheel_width * wheel_width)}"
                    izz="${(1/12) * 0.5 * (3 * wheel_radius * wheel_radius + wheel_width * wheel_width)}"
                    ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left_"  name="wheel_link"/>
    <xacro:wheel_link prefix="right_" name="wheel_link"/>

    <link name= "caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius = "0.05"/>
            </geometry>
            <origin xyz = "0 0 -0.025" rpy = "${pi / 2} 0 0"/>
            <material name= "black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius = "0.05"/>
            </geometry>
            <origin xyz = "0 0 -0.025" rpy = "${pi / 2} 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.2"/>
            <inertia
                ixx="${(2/5) * 0.2 * 0.05 * 0.05}"
                iyy="${(2/5) * 0.2 * 0.05 * 0.05}"
                izz="${(2/5) * 0.2 * 0.05 * 0.05}"
                ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <joint name = "base_footprint_joint" type="fixed" >
        <parent link="base_footprint_link" />
        <child link="base_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
    </joint>

    <joint name="base_imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-0.15 -0.225 0" rpy="0 1 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-0.15 0.225 0" rpy="0 1 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_height} 0 -0.025" rpy="0 0 0"/>
    </joint>

</robot>